#!/usr/bin/env perl

use strict;
use warnings;
use FindBin;

my $usage = <<_EOUSAGE_;


   usage: $0 <sqlite.db> <command> <input> [...]


     <commands>: 

         * Initial creation of the Trinotate sqlite database and downloading of the required data sets
              
             Trinotate <sqlite.db> create /path/to/TRINOTATE_DATA_DIR

                 The sqlite.db file is created as named and search databases are downloaded into /path/to/TRINOTATE_DATA_DIR
                 (Note, if EggnogMapper is installed and env var EGGNOG_DATA_DIR is NOT set, will additionally download those data too into TRINOTATE_DATA_DIR !) 

         * Initial import of transcriptome and protein data:

             Trinotate <sqlite.db> init --gene_trans_map <file> --transcript_fasta <file> --transdecoder_pep <file>

         * Transdecoder protein search results:

             Trinotate <sqlite.db> LOAD_swissprot_blastp <file>
             Trinotate <sqlite.db> LOAD_pfam <file>
             Trinotate <sqlite.db> LOAD_deeptmhmm <file>
             Trinotate <sqlite.db> LOAD_signalp <file>
             Trinotate <sqlite.db> LOAD_EggnogMapper <file>

          * Trinity transcript search results:

             Trinotate <sqlite.db> LOAD_swissprot_blastx <file>
             Trinotate <sqlite.db> LOAD_infernal <file>
             

          * Load custom blast results using any searchable database

             Trinotate <sqlite.db> LOAD_custom_blast --outfmt6 <file> --prog <blastp|blastx> --dbtype <database_name>


          * report generation:

             Trinotate <sqlite.db> report [ -E (default: 1e-5) ] [--pfam_cutoff DNC|DGC|DTC|SNC|SGC|STC (default: DNC=domain noise cutoff)]


_EOUSAGE_

;

unless (scalar @ARGV >= 2) { die $usage; }

my $sqlite_db = shift @ARGV;
my $command = shift @ARGV;

unless (-s $sqlite_db) {
    die "Error, cannot locate $sqlite_db database file. Be sure it's in your current directory.";
}

if ($command ne 'report' && ! @ARGV) {
    die $usage . "\n\nMissing parameter.\n\n";
}

my %commands = map { + $_ => 1 } qw(LOAD_swissprot_blastp LOAD_swissprot_blastx 
                                    LOAD_pfam LOAD_deeptmhmm LOAD_signalp LOAD_infernal
                                    LOAD_EggnogMapper
                                    LOAD_custom_blast
                                    report init);

unless (exists $commands{$command}) {
    die "$usage\nError, do not recognize command: $command\n";
}

my $util_dir = "$FindBin::RealBin/util";
my $loaders_dir = "$util_dir/trinotateSeqLoader";

unless (@ARGV) {
    @ARGV = (""); # to avoid error messages inusing $ARGV[0] below
}

my %command_to_params = ( 
    # protein-based
    'LOAD_swissprot_blastp' => "$loaders_dir/Trinotate_BLAST_loader.pl --sqlite $sqlite_db --outfmt6 $ARGV[0] --prog blastp --dbtype Swissprot",
    'LOAD_trembl_blastp' => "$loaders_dir/Trinotate_BLAST_loader.pl --sqlite $sqlite_db --outfmt6 $ARGV[0] --prog blastp --dbtype TrEMBL",
    'LOAD_pfam'  => "$loaders_dir/Trinotate_PFAM_loader.pl --sqlite $sqlite_db --pfam $ARGV[0]",
    'LOAD_deeptmhmm' => "$loaders_dir/Trinotate_DeepTmHMM_loader.pl --sqlite $sqlite_db --tmhmm $ARGV[0]",
    'LOAD_signalp' => "$loaders_dir/Trinotate_SIGNALP_loader.pl --sqlite $sqlite_db --signalp $ARGV[0]",
    'LOAD_EggnogMapper' => "$loaders_dir/Trinotate_EggnogMapper_loader.pl --sqlite $sqlite_db --emapper $ARGV[0]",
    
    
    # transcript-based
    'LOAD_swissprot_blastx' => "$loaders_dir/Trinotate_BLAST_loader.pl --sqlite $sqlite_db --outfmt6 $ARGV[0] --prog blastx --dbtype Swissprot",
    'LOAD_trembl_blastx' => "$loaders_dir/Trinotate_BLAST_loader.pl --sqlite $sqlite_db --outfmt6 $ARGV[0] --prog blastx --dbtype TrEMBL",
    'LOAD_infernal' => "$loaders_dir/Trinotate_Infernal_loader.pl --sqlite $sqlite_db --infernal $ARGV[0]",
    
    # custom blast searches
    'LOAD_custom_blast' => "$loaders_dir/Trinotate_BLAST_loader.pl --sqlite $sqlite_db @ARGV",
    
    
    );



if (my $cmd = $command_to_params{$command}) {
    &process_cmd($cmd);
}
elsif ($command eq "report") {
    ## generate Trinotate report.
    my $cmd = "$FindBin::RealBin/util/Trinotate_report_writer.pl --sqlite $sqlite_db @ARGV";
    &process_cmd($cmd);
    
}
elsif ($command eq "init") {
    # populate sequence and gene/trans/orf data
    my $cmd = "$FindBin::RealBin/util/trinotateSeqLoader/TrinotateSeqLoader.pl --sqlite $sqlite_db @ARGV --bulk_load";
    &process_cmd($cmd);
}
else {
    die "Error, do not recognize command: $command ";
}



exit(0);

####
sub process_cmd {
    my ($cmd) = @_;

    print STDERR "CMD: $cmd\n";
    my $ret = system($cmd);
    if ($ret) {
        die "Error, cmd: $cmd died with ret $ret";
    }

    return;
}
